### ISSUE TITLE
Incorrect GitHub Link in Cargo.toml

### ISSUE THREAD

**Issue by RealArcanePhysics** [craftserverbot/elytra-ping#3]
The link you're using in your Cargo.toml appears to be incorrect. You have it set to [https://github.com/craftserver/elytra-ping](https://github.com/craftserver/elytra-ping), when it should be [https://github.com/craftserverbot/elytra-ping](https://github.com/craftserverbot/elytra-ping).

**Comment by lewisfm** [comment]
Thanks for letting me know!
