### ISSUE TITLE
Can't access `BedrockServerInfo` fields

### ISSUE THREAD

**Issue by GoodLucky777** [craftserverbot/elytra-ping#4]
Because `BedrockServerInfo` fields are not public, you can not access data.

https://github.com/craftserverbot/elytra-ping/blob/364e186e3bb9e9e5b64e3b72205a57ec2ab0ef49/src/bedrock.rs#L17-L32

**Comment by MatthewCash** [comment]
You can convert it to a `JavaServerInfo` and get the players and description, but that's it for some reason.

**Comment by lewisfm** [comment]
Oops 😅

**Comment by lewisfm** [comment]
Should be fixed in v5.1.0
